enroll/urls.py
from django.urls import path
from . import views

app_name = 'enroll'
urlpatterns = [
    path('', views.index, name = 'enroll'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name = 'home'),
    path('subscribe', views.subscribe, name = 'subscribe'),
]

nano/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from posts import views as post_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('contactus/', include('contactus.urls')),
    path('register/', include('enroll.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls', namespace='posts')),
    # path('posts/', post_views.post_home),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import (
    post_list,
    post_create,
    post_detail,
    post_update,
    post_delete,
)

app_name = 'posts'
urlpatterns = [
    # path('', views.post_home, name = 'posts'),
    path('', post_list, name = 'post_list'),
    path('create/', post_create, name = 'post_create'),
    # path('detail/<int:id>', post_detail, name = 'post_detail'),
    path('<int:id>/', post_detail, name = 'post_detail'),  # posts/id
    path('<int:id>/edit/', post_update, name = 'post_update'),
    path('<int:id>/delete/', post_delete, name = 'post_delete'),

]

enroll/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.utils import timezone 

class Enroll(models.Model):
    name = models.CharField(max_length=50, verbose_name='نام')
    email = models.EmailField(verbose_name='ایمیل')
    phone_regex = RegexValidator(regex=r'^(09)\d{9,9}$', message='شماره وارد شده صحیح نیست')
    mobile = models.CharField(validators=[phone_regex], max_length=11)
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name = 'ثبت نام'
        verbose_name_plural = 'ثبت نام ها'

    def __str__(self):
        return self.name 

enroll/forms.py
from django import forms
from django.core.validators import RegexValidator
from .models import Enroll

class EnrollForm(forms.Form):
    name = forms.CharField(max_length=50)
    email = forms.EmailField()
    # mobile = PhoneNumberField()
    phone_regex = RegexValidator(regex=r'^(09)\d{9,9}$', message='شماره وارد شده صحیح نیست')
    mobile = forms.CharField(validators=[phone_regex], max_length=11)

enroll/views.py
from django.shortcuts import render, redirect

from .forms import EnrollForm
from .models import Enroll


def index(request):
    if request.method == 'POST':
        form = EnrollForm(request.POST)
        if form.is_valid():
            Enroll.objects.create(
                    name = form.cleaned_data['name'],
                    email = form.cleaned_data['email'],
                    mobile = form.cleaned_data['mobile'],
                )
            return redirect('enroll:enroll')
    else:
        form = EnrollForm()
        return render(request, 'enroll/index.html')

    return render(request, 'enroll/index.html', {'form':form})

enroll/templates/layout/head/head.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="   کلینیک علوم و فناوری نانو  ">
    <meta name="keywords" content=" نانو ، کنکور ، المپیاد ، جشنواره خوارزمی">
    <meta name="Developer" content="mosi.php@gmail.com">

    <title> کلینیک علوم و فناوری نانو </title>

    {% load static %}

    <!--     script   -->

    <script src="{% static 'home/js/jquery-2.2.3.min.js' %}"></script>
    <script src="{% static 'home/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'home/js/responsiveslides.min.js' %}"></script>
    <script src="{% static 'home/js/script.js' %}"></script>


    <!--    StyleSheet -->
    <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/bootstrap-rtl.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/lib.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>

enroll/templates/layout/head/header.html
<header>
    <div class="container-fluid">
	<div class="row">
		<nav class="navbar navbar-default navbar-fixed-top " id="my-nav">
			<div class="container-fluid">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
					        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

					<ul class="nav navbar-nav">
						<li class="active"><a href="index.php">
							<i class="fa fa-home fa-lg homepage"></i>
							<span class="sr-only">(current)</span></a></li>
						<li><a href="#"> درباره ما </a></li>
						<li><a href="#"> تماس با ما </a></li>
						<li><a href="{% url 'posts:post_list' %}"> وبلاگ </a></li>
						<li><a href="gallery.php"> گالری تصاویر </a></li>
					</ul>
					<ul class="nav navbar-nav navbar-left my-login ">
						<li><a href="{% url 'enroll:enroll' %}"><span class="fa fa-user myRegister "></span> ثبت نام </a></li>
					</ul>

				</div><!-- /.navbar-collapse -->
			</div><!-- /.container-fluid -->
		</nav>
	</div>
</header>