home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name = 'home'),
    path('subscribe', views.subscribe, name = 'subscribe'),
]

nano/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from posts import views as post_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('contactus/', include('contactus.urls')),
    path('register/', include('enroll.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls', namespace='posts')),
    # path('posts/', post_views.post_home),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resources/templates/layout/sections/footer.html
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-4 pull-right">
                <h3 class="text-right">تماس با ما</h3>
                <ul>
                    <li class="pull-right">
                        <a href="">
                            <span class="material-icons pull-right" style="font-size: 25px">place</span>
                            <span class="titr"> آران و بیدگل - خیابان امام - کوچه 20</span>
                        </a>
                    </li>
                    <li class="pull-right">
                        <a href="">
                            <span class="material-icons pull-right" style="font-size: 25px">phone</span>
                            <span class="titr">09355739363 - 03154755201 </span>
                        </a>
                    </li>
                    <li class="pull-right">
                        <a href="">
                            <span class="material-icons pull-right" style="font-size: 25px">email</span>
                            <span class="titr">mosi.ghorbani@gmail.com </span>
                        </a>
                    </li>
                    <li class="pull-right">
                        <a href="">
                            <span class="material-icons pull-right" style="font-size: 25px">star</span>
                            <span class="titr">تماس همه روزه از 8 تا 20 </span>
                        </a>
                    </li>
                    <br>
                    <br>
                    <li class="pull-right">
                        <ul id="social_network" class="pull-right">
                            <li><a href=""><img src="static/img/social/facebook.png" alt=""></a></li>
                            <li><a href=""><img src="static/img/social/youtube.png" alt=""></a></li>
                            <li><a href=""><img src="static/img/social/telegram.png" alt=""></a></li>
                            <li><a href=""><img src="static/img/social/line.png" alt=""></a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="col-md-4 pull-right">
                <h3 class="text-right">دسترسی سریع</h3>
                <ul>
                    <li class="pull-right">
                        <a href="">
                            <span class="material-icons pull-right" style="font-size: 25px">place</span>
                            <span class="titr"><a href="">ستاد نانو</a></span>
                        </a>
                    </li>
                    <li class="pull-right">
                        <a href="">
                            <span class="material-icons pull-right" style="font-size: 25px">place</span>
                            <span class="titr"><a href=""> باشگاه نانو دانش آموزی</a></span>
                        </a>
                    </li>
                    <li class="pull-right">
                        <a href="">
                            <span class="material-icons pull-right" style="font-size: 25px">place</span>
                            <span class="titr"><a href=""> نخبگان ریاست جمهوری</a></span>
                        </a>
                    </li>
                    <li class="pull-right">
                        <a href="">
                            <span class="material-icons pull-right" style="font-size: 25px">place</span>
                            <span class="titr"><a href=""> آموزش و پرورش شهرستان آران و بیدگل</a></span>
                        </a>
                    </li>
                    <li class="pull-right">
                        <a href="">
                            <span class="material-icons pull-right" style="font-size: 25px">place</span>
                            <span class="titr"><a href=""> آموزش دوره های نانو تکنولوژِی</a></span>
                        </a>
                    </li>

                </ul>
            </div>
            <div class="col-md-4 pull-right">
                <form class="form-inline row" id="subscribe" action="{% url 'home:subscribe' %}" method='POST'>
                    {% csrf_token %}
                    <div class="form-group col-md-3">
                        <button type="submit" class="btn btn-default ">مشترک شوید</button>
                    </div>
                    <div class="form-group col-md-9">
                        <input type="email" name="email" class="form-control" id="user_email" placeholder="ایمیل شما">
                    </div>
                </form>
                <ul id="licence_logo">
                    <li style="width: auto"><img src="static/img/licence_1.png" alt="licence"></li>
                    <li style="width: auto"><img src="static/img/licence_2.png" alt="licence"></li>
                </ul>
            </div>
        </div>
    </div>

</footer>

resources/templates/layout/sections/modal.html
<div class="modal fade" id="register" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title text-center" id="myModalLabel">فرم ثبت نام </h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label for="full_name" class="col-sm-2 pull-right control-label">نام و نام خانوادگی</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="full_name"
                                   placeholder="نام کامل خود را وارد نمایید ..">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="national_code" class="col-sm-2 pull-right control-label">کدملی</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="national_code" placeholder="1234567890">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="mobile_number" class="col-sm-2 pull-right control-label">تلفن همراه</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="mobile_number" placeholder="0912345678">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="email" class="col-sm-2 pull-right control-label">ایمیل</label>
                        <div class="col-sm-10">
                            <input type="email" class="form-control" id="email" placeholder="ali@gmail.com">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-4 col-sm-4">
                            <button type="submit" class="btn btn-default">ثبت نام</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/templates/layout/sections/services.html
<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3 class="title"> <span> خدمات ما </span></h3>
            </div>
            <div class="col-md-4">
                <a href="#" class="service-box" style="background-color: #3498db">
                    <div class="text-center"><img src="static/img/dna.png" alt=""></div>
                    <div class="text-center"><h4>المپیاد </h4></div>
                    <div class="text-center">  <h5> مدرس و بنیان گذار موسسه </h5> </div>
                </a>
            </div>
            <div class="col-md-4">
                <a href="#" class="service-box" style="background-color: #16a085">
                    <div class="text-center"><img src="static/img/satellite.png" alt=""></div>
                    <div class="text-center"><h4>جشنواره خوارزمی</h4></div>
                    <div class="text-center">  <h5> مدرس و بنیان گذار موسسه </h5> </div>
                </a>
            </div>
            <div class="col-md-4">
                <a href="#" class="service-box" style="background-color: #e74c3c">
                    <div class="text-center"><img src="static/img/flasks.png" alt=""></div>
                    <div class="text-center"><h4>تقویتی کنکور</h4></div>
                    <div class="text-center">  <h5> مدرس و بنیان گذار موسسه </h5> </div>
                </a>
            </div>
            <div class="col-md-4">
                <a href="#" class="service-box" style="background-color: #8e44ad">
                    <div class="text-center"><img src="static/img/microscope.png" alt=""></div>
                    <div class="text-center"><h4>نانو فناوری</h4></div>
                    <div class="text-center">  <h5> مدرس و بنیان گذار موسسه </h5> </div>
                </a>
            </div>
            <div class="col-md-4">
                <a href="#" class="service-box" style="background-color: #d35400">
                    <div class="text-center"><img src="static/img/molecular.png" alt=""></div>
                    <div class="text-center"><h4>کارگاه</h4></div>
                    <div class="text-center">  <h5> مدرس و بنیان گذار موسسه </h5> </div>
                </a>
            </div>
            <div class="col-md-4">
                <a href="#" class="service-box" style="background-color: #2c3e50">
                    <div class="text-center"><img src="static/img/atom.png" alt=""></div>
                    <div class="text-center"><h4>تالیف</h4></div>
                    <div class="text-center">  <h5> مدرس و بنیان گذار موسسه </h5> </div>
                </a>
            </div>
        </div>
    </div>

</section>

resources/templates/layout/sections/slideshow.html
<section id="slideshow">
    <ul class="rslides">
        <li><img src="static/img/1.jpg" alt=""></li>
        <li><img src="static/img/2.jpg" alt=""></li>
        <li><img src="static/img/3.jpg" alt=""></li>
    </ul>
</section>
<section id="main_titr">
    <h2 class="text-center">
       <span class="text-center">
           برآن شدیم با طرحی نو و تفکری جدید به خدمت همشهریان عزیز ایفای نقش کنیم
       </span>
        <span class="text-center">
            تا آخر راه همراه شماییم
        </span>

    </h2>
</section>

resources/templates/layout/sections/teammate.html
<section id="teammate">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3 class="title"> <span> همکاران ما </span></h3>
            </div>
            <div class="col-md-4">
                <div class="teammate-box">
                    <div class="text-center"><img src="static/img/boss.png" alt=""></div>
                    <div class="text-center"><h4>دکتر قربانی</h4></div>
                    <div class="text-center">  <h5> مدرس و بنیان گذار موسسه </h5> </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="teammate-box">
                    <div class="text-center"><img src="static/img/woman.png" alt=""></div>
                    <div class="text-center"><h4>دکتر قربانی</h4></div>
                    <div class="text-center">  <h5> مدرس و بنیان گذار موسسه </h5> </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="teammate-box">
                    <div class="text-center"><img src="static/img/woman.png" alt=""></div>
                    <div class="text-center"><h4>دکتر قربانی</h4></div>
                    <div class="text-center">  <h5> مدرس و بنیان گذار موسسه </h5> </div>
                </div>
            </div>
        </div>
    </div>

</section>